apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-products
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: api-products
  namespaceSelector:
    matchNames:
      - backend
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-auth
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: api-auth
  namespaceSelector:
    matchNames:
      - backend
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
