apiVersion: v1
kind: Service
metadata:
  name: api-products
  namespace: backend
  labels: 
    app: api-products
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: api-products
